language: ruby
cache: bundler
rvm: 2.2.0

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - psql -c 'create database "hound_test";' -U postgres

services:
  - redis-server

notifications:
  slack:
    secure: BdIl+dAUtA6gLB9lk/4xNYoERF+yIcFp8J+wNAzMV4eNjEOC6fAaZyFCxCjv2CjDT1lWxWLPzfSyoCDjxI7A5ykQLlcI25d7Pk0SjclOq47BqIyZRSKt1ZMHqh928YfRZZKx4AUibXsx5draI74+5btU11ocV3wVKIB9yAXhvig=
    on_success: change
    on_failure: always
