# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

linters:
  AltText:
    enabled: false

  ClassAttributeWithStaticValue:
    enabled: false

  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  ConsecutiveSilentScripts:
    enabled: false
    max_consecutive: 2

  EmptyScript:
    enabled: false

  HtmlAttributes:
    enabled: false

  ImplicitDiv:
    enabled: false

  LeadingCommentSpace:
    enabled: false

  LineLength:
    enabled: false
    max: 80

  MultilinePipe:
    enabled: false

  MultilineScript:
    enabled: false

  ObjectReferenceAttributes:
    enabled: false

  RuboCop:
    enabled: false

  RubyComments:
    enabled: false

  SpaceBeforeScript:
    enabled: false

  SpaceInsideHashAttributes:
    enabled: false
    style: space

  TagName:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UnnecessaryInterpolation:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false
