version: 2
jobs:
  build:
    working_directory: ~/hound
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          CIRCLECI: true
          PGHOST: 127.0.0.1
          PGUSER: houndci
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: houndci
          POSTGRES_DB: houndci-test
          POSTGRES_PASSWORD: ""
      - image: redis:3.2.10-alpine
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: houndci-{{ checksum "Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: houndci-yarn-{{ checksum "yarn.lock" }}

      - type: cache-restore
        name: Restore apt cache
        key: houndci-apt-{{ checksum "Gemfile.lock" }}

      # Install System Dependencies from cache (for capybara-webkit)
      - run: sudo dpkg -i /home/circleci/.cache/apt/archives/*.deb || true

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Yarn install
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn && yarn install

      - type: cache-save
        name: Store bundle cache
        key: houndci-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: houndci-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

      - type: cache-save
        name: Store apt cache
        key: houndci-apt-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/.cache/apt

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Wait for Redis
      - run: dockerize -wait tcp://localhost:6379 -timeout 1m

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: xvfb-run --auto-servernum bundle exec rake
