AndOr:
  Description: 'Use &&/|| instead of and/or.'
  Enabled: true

Blocks:
  Description: >
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  Enabled: true

BlockComments:
  Description: 'Do not use block comments.'
  Enabled: true

BracesAroundHashParameters:
  # Valid values are: braces, no_braces
  EnforcedStyle: no_braces
  Enabled: true

ClassAndModuleCamelCase:
  Description: 'Use CamelCase for classes and modules.'
  Enabled: true

ClassMethods:
  Description: 'Use self when defining module/class methods.'
  Enabled: true

ColonMethodCall:
  Description: 'Do not use :: for method call.'
  Enabled: true

ConstantName:
  Description: 'Constants should use SCREAMING_SNAKE_CASE.'
  Enabled: true

DefWithParentheses:
  Description: 'Use def with parentheses when there are arguments.'
  Enabled: true

DefWithoutParentheses:
  Description: >
                 Omit the parentheses when the method doesn't accept
                 any arguments.
  Enabled: true

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  Style: 'leading'
  Enabled: true

EmptyLineBetweenDefs:
  Description: 'Use empty lines between defs.'
  Enabled: true

EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: true

EndOfLine:
  Description: 'Use Unix-style line endings.'
  Enabled: true

FinalNewline:
  Description: 'Checks for a final newline in a source file.'
  Enabled: true

HashSyntax:
  Description: >
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  EnforcedStyle: ruby19
  Enabled: true

IfWithSemicolon:
  Description: 'Never use if x; .... Use the ternary operator instead.'
  Enabled: true

IndentationWidth:
  Description: 'Use 2 spaces for indentation.'
  Enabled: true

LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80
  Enabled: true

MethodCallParentheses:
  Description: 'Do not use parentheses for method calls with no arguments.'
  Enabled: true

MethodName:
  # Valid values are: snake_case, camelCase
  Description: 'Use the configured style when naming methods.'
  EnforcedStyle: snake_case
  Enabled: true

Not:
  Description: 'Use ! instead of not.'
  Enabled: true

ParenthesesAroundCondition:
  Description: >
                 Don't use parentheses around the condition of an
                 if/unless/while.
  Enabled: true

ReduceArguments:
  Description: 'Name reduce arguments |a, e| (accumulator, element)'
  Enabled: true

RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  Enabled: true

RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: true

RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: true

SpaceAroundOperators:
  Description: 'Use spaces around operators.'
  Enabled: true

SpaceAroundBlockBraces:
  Description: >
                 Checks that block braces have or don't have surrounding space.
                 For blocks taking parameters, checks that the left brace has
                 or doesn't have trailing space.
  # Valid values are: space_inside_braces, no_space_inside_braces
  EnforcedStyle: space_inside_braces
  # Valid values are: space, no_space
  EnforcedStyleForEmptyBraces: no_space
  # Space between { and |. Overrides EnforcedStyle if there is a conflict.
  SpaceBeforeBlockParameters: true
  Enabled: true

SpaceInsideParens:
  Description: 'No spaces after ( or before ).'
  Enabled: true

SpaceInsideBrackets:
  Description: 'No spaces after [ or before ].'
  Enabled: true

SpaceAfterColon:
  Description: 'Use spaces after colons.'
  Enabled: true

SpaceAfterComma:
  Description: 'Use spaces after commas.'
  Enabled: true

SpaceAfterControlKeyword:
  Description: 'Use spaces after if/elsif/unless/while/until/case/when.'
  Enabled: true

SpaceAfterMethodName:
  Description: >
                 Never put a space between a method name and the opening
                 parenthesis.
  Enabled: true

SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: true

SpaceAfterSemicolon:
  Description: 'Use spaces after semicolons.'
  Enabled: true

SpaceAroundEqualsInParameterDefault:
  Description: >
                 Use spaces around the = operator when assigning default
                 values in def params.
  Enabled: true

SpaceBeforeModifierKeyword:
  Description: 'Put a space before the modifier keyword.'
  Enabled: true

SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  # Valid values (for both parameters) are: space, no_space
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  Enabled: true

StringLiterals:
  # Valid values (denoting the preferred quote delimiters) are:
  # single_quotes, double_quotes
  EnforcedStyle: single_quotes
  Enabled: true

SymbolName:
  Description: 'Symbol literals should use snake_case.'
  Enabled: true

Tab:
  Description: 'No hard tabs.'
  Enabled: true

TrailingBlankLines:
  Description: 'Checks for superflous trailing blank lines.'
  Enabled: true

TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  Enabled: true

UnlessElse:
  Description: >
                 Never use unless with else. Rewrite these with the positive
                 case first.
  Enabled: true

VariableName:
  Description: 'Use the configured style when naming variables.'
  # Valid values are: snake_case, camelCase
  EnforcedStyle: snake_case
  Enabled: true
