Style/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AsciiIdentifiers:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BlockNesting:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CyclomaticComplexity:
  Enabled: false

Style/DeprecatedHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FlipFlop:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/LineLength:
  Max: 80

Style/MethodLength:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: false

Style/ParameterLists:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - is_

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConditionPosition:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/ElseLayout:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/InvalidCharacterLiteral:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: false

Lint/LiteralInInterpolation:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RequireParentheses:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/Void:
  Enabled: false

Rails/Delegate:
  Enabled: false
