FileName:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

MethodLength:
  Enabled: false

ModuleFunction:
  Enabled: false

ParameterLists:
  Enabled: false

Proc:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

VariableInterpolation:
  Enabled: false

LineLength:
  Max: 80

DotPosition:
  EnforcedStyle: trailing

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'inject'
    detect: 'detect'
    find_all: 'select'
